small improvements to error messages

diff --git a/config-pin b/config-pin
--- a/config-pin
+++ b/config-pin
@@ -582,16 +582,16 @@ P9_46_CAPE=""
 
 
 echo_err () {
-	echo "$@" 1>&2
+	echo -e "$@" 1>&2
 }
 
 echo_std () {
-	echo "$@"
+	echo -e "$@"
 }
 
 echo_dbg () {
 	if [ -n "$DEBUG" ] ; then
-		echo "$@" 1>&2
+		echo -e "$@" 1>&2
 	fi
 }
 
@@ -837,7 +837,7 @@ load_cape () {
 			# Expand filename using shell globbing
 			for FILE in $SLOTS ; do
 				echo_std Loading $DTBO overlay
-				sudo -A su -c "echo $DTBO > $SLOTS" || (echo_err "Error loading device tree overlay file: $DTBO" && exit 1)
+				sudo -A su -c "echo $DTBO > $SLOTS" || (echo_err "Error loading device tree overlay file: $DTBO\n see dmesg for details" && exit 1)
 				sleep 1
 			done
 		fi
